### ISSUE TITLE
purchase handling

### ISSUE THREAD

**Issue by njason** [MakerBar/accountant_bot#1]
We should make a standard procedure for submitting purchases for the space through slack. The workflow am thinking is:
1. A purchase is made for the space
2. A picture a of the receipt is uploaded to slack as a message to treasurer
3. The treasurer approves the purchase using a accountant_bot command to log the purchase for the member who made the purchase( i.e _@accountant_bot purchase @jason 5.99_)
4. accountant_bot deducts the purchase amount from the member's dues

Only the treasurer could use the purchase command of accountant_bot

**Comment by BertHartm** [comment]
I'll give you access to xero, which does most of that
